site_name: "MTUOC: A Practical Course on Machine Translation Technologies"
site_description: An open online course on machine translation technologies with MTUOC
site_author: Antoni Oliver and Sergi Alvarez-Vidal

theme:
  name: material
  features:
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy

nav:
  - Home: index.md
  - About this Course: about.md
  - How to Navigate this Course: how-to-navigate.md
  
  - Module 1. Deployment, Integration and Evaluation:
# INICI_WIKI_MODUL_1
    - 1. The Mtuoc Project: module-1/1.-The-MTUOC-project.md
    - 2. Open Neural Machine Translation Models: module-1/2.-Open-Neural-Machine-Translation-models.md
    - 2.1. Opusmt: module-1/2.1.-OpusMT.md
    - 2.2. Nllb: module-1/2.2.-NLLB.md
    - 3. Integration Into Cat Tools: module-1/3.-Integration-into-CAT-tools.md
    - 3.1.B. Omegat Plugin: module-1/3.1.b.-OmegaT-plugin.md
    - 4. Large Language Models And Translation: module-1/4.-Large-Language-Models-and-translation.md
    - 5. Large Language Models Integration Into Mtuoc Server: module-1/5.-Large-Language-models-integration-into-MTUOC-server.md
    - 5.1. Salamandrata: module-1/5.1.-SalamandraTA.md
    - 5.2. Gemma: module-1/5.2.-Gemma.md
    - Tutorial: Integrating Free Nmt And Llms Into Cat Tools With Mtuoc: module-1/Tutorial:-integrating-free-NMT-and-LLMs-into-CAT-tools-with-MTUOC.md
    - _Sidebar: module-1/_Sidebar.md
    - Home: module-1/home.md
# FINAL_WIKI_MODUL_1

  - Module 2. Corpus Engineering:
      - Overview: module-2/index.md

  - Module 3. NMT Training and Fine-tuning:
      - Overview: module-3/index.md

  - Module 4. LLMs for Translation:
      - Overview: module-4/index.md

  - Final project: final-project.md
  - Glossary: glossary.md
  - Troubleshooting: troubleshooting.md
  - References: references.md
  - Credits and licence: credits.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - fenced_code
  - attr_list
  
extra_css:

  - stylesheets/extra.css
